Anne-edit-introduction
carpentries-incubator/lesson-parallel-python pull request #105
Opened 2022-11-21 15:41 UTC by theredgeek

A few styling changes in some descriptions changed the variables' names to be consistent and reflect the meaning of the code.

2022-11-22 10:46 UTC, PabRod commented
Some context for @jhidding: 

@theredgeek discussed with me some ideas about this in a meeting yesterday. I agreed, so consider my review as approved :)

2022-11-22 11:28 UTC, jhidding requested changes
The code changes are all good. The phrasing of some of the sentences could be better. Overall the text in this section is a bit too wordy for my taste. We should think about the target audience here: teachers of the course. The allegory of working people is a nice example that helps a teacher, but we shouldn't overdo it.

2022-12-07 13:37 UTC, liekelotte commented on _episodes/01-introduction.md
> +Our computation involves **independent work** if the results of the application of each of our functions are independent from the results of the application of the rest. In that instance we can struc
Hey Johan, since Anne has left us, could you make the requested change and merge this PR? Thanks in advance :)

2023-01-03 19:30 UTC, jhidding commented on _episodes/01-introduction.md
> +Our computation involves **independent work** if the results of the application of each of our functions are independent from the results of the application of the rest. In that instance we can struc
Komt in orde, ik ga hier morgen aan werken.

2025-03-25 14:51 UTC, closed without merging